---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rstrind/public_html/
    - /bin/rm -rf $DEPLOYPATH/*  # Clear old files in public_html
    - /bin/rm -rf $DEPLOYPATH/.* 2>/dev/null || true  # Clear hidden files safely
    - /bin/cp -R Induction-App/public/* $DEPLOYPATH/
    - /bin/cp -R Induction-App/public/.htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/cp -R Induction-App/.env $DEPLOYPATH/ 2>/dev/null || true  # Copy .env if needed
    - /bin/chmod 644 $DEPLOYPATH/.env 2>/dev/null || true
    - echo "Deployment completed successfully!"
