---
deployment:
  tasks:
    - export DEPLOYPATH=/home/rstrind/public_html/
    - /bin/rm -rf $DEPLOYPATH/* || true
    - /bin/rm -rf $DEPLOYPATH/.* 2>/dev/null || true
    - /bin/cp -R Induction-App/public/* $DEPLOYPATH/ || true
    - /bin/cp -R Induction-App/public/.htaccess $DEPLOYPATH/ 2>/dev/null || true
    - echo "Deployed only public files!"
