---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tstind/public_html/
    - /bin/rm -rf $DEPLOYPATH/* || true
    - /bin/rm -rf $DEPLOYPATH/.* 2>/dev/null || true
    - /bin/cp -r inductionapp/Induction-App/public/* $DEPLOYPATH/ || true
    - /bin/cp -r inductionapp/Induction-App/public/.htaccess $DEPLOYPATH/ 2>/dev/null || true
    - /bin/chmod 644 $DEPLOYPATH/.htaccess || true
    - /bin/chmod 755 $DEPLOYPATH || true
    - echo "Deployed Laravel public files from correct path!"
